[default]
DJANGO_SECRET_KEY = 'pass'
DJANGO_ALLOWED_HOSTS = ['chat.sspx.ru', '127.0.0.1', '10.10.20.170', '10.10.20.230', '185.69.55.213']

[development]
debug = true            # true | false
log_level = 'DEBUG'     # DEBUG | INFO
DJANGO_DEBUG = true

[production]
debug = false
log_level = 'INFO'      # DEBUG | INFO
DJANGO_DEBUG = false
